name:                haskell-pyls
version:             0.1.0
github:              illright/haskell-pyls
license:             MIT
author:              Anna Boronina, Lev Chelyadinov
maintainer:          leva181777@gmail.com
copyright:           2021 Anna Boronina, Lev Chelyadinov

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/illright/haskell-pyls#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - text >= 1.2.4.1 && < 2
  - lsp >= 1.2.0.0 && < 2
  - transformers >= 0.5.6.2 && < 1
  - language-python >= 0.5.8 && < 1
  - containers >= 0.6.2.1 && < 1
  - lens >= 4.19.2 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-pyls-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - haskell-pyls
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
